name: CD Orchestrator Deployment

permissions:
  id-token: write
  contents: write
  security-events: write
  actions: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        type: string
        required: true
      AWS_IAM_ROLE:
        type: string
        required: true
      K8S_MANIFEST_REPO:
        type: string
      K8S_VALUES_FILE:
        type: string
jobs: 

  identify_dev_environment:
     if: ${{ startsWith(github.ref, 'refs/heads/release') }}
     runs-on: ubuntu-latest
     outputs:
       dev_env: ${{ steps.set-env.outputs.dev_env }}
     steps:
       - name: Set environment variable based on branch name
         id: set-env
         run: |
           if [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
             git_env=dev1
           elif [[ "${{ github.ref }}" == refs/heads/release-sq*/* ]]; then
            git_env=dev-$(echo "${{ github.ref }}" | sed -E 's|refs/heads/release-([^/]+)/.*|\1|')
           fi
           echo "dev_env=$git_env" >> $GITHUB_OUTPUT
           echo "Your DEV Environment: $git_env"
  test:
      name: Unit Test
      needs: compile
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Application Code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
        
        - name: Checkout reusable code
          uses: actions/checkout@v4
          with: 
            repository: ehteshamkhaja/enterprise-reusable-workflows
            ref: feature/cicd-publish
            path: reusable-workflows
            token: ${{ secrets.DEVOPS_WORKFLOW_TOKEN }}

